services:
  galim-pro-monitor:
    build: .
    container_name: galim-pro-monitor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

